version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysqldb
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tokoto
    volumes:
      - mysql:/data/mysql
    restart: unless-stopped

  spring:
    build: .
    container_name: spring-inventaris
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/tokoto
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    volumes:
      - inventaris_data:/app/static/image/upload
      - inventaris_data:/app/static/image/categories
      - inventaris_data:/app/static/image/message
      - inventaris_data:/app/static/image/users
  volumes:
    inventaris_data:
      driver: local